Repository Groot-GT/groot-server, pull requests merged in 2023-05, with the labels that each got.

#3 feat(MS-26): 노드 CRUD 기능 추가
  build.gradle
  src/main/java/com/groot/mindmap/MindmapApplication.java
  src/main/java/com/groot/mindmap/exception/ControllerAdvice.java
  src/main/java/com/groot/mindmap/node/controller/NodeController.java
  src/main/java/com/groot/mindmap/node/domain/Node.java
  src/main/java/com/groot/mindmap/node/dto/NodeRequest.java
  src/main/java/com/groot/mindmap/node/dto/NodeResponse.java
  src/main/java/com/groot/mindmap/node/repository/NodeRepository.java
  src/main/java/com/groot/mindmap/node/service/NodeService.java
Labels: enhancement

#4 feat(MS-27): 유저의 입장 및 퇴장 시의 해당되는 메세지 pub/sub 추가
  src/main/java/com/groot/mindmap/config/RedisConfiguration.java
  src/main/java/com/groot/mindmap/config/WebsocketConfiguration.java
  src/main/java/com/groot/mindmap/message/domain/EntryMessage.java
  src/main/java/com/groot/mindmap/message/domain/ExitMessage.java
  src/main/java/com/groot/mindmap/message/domain/Message.java
  src/main/java/com/groot/mindmap/message/repository/RedisRepository.java
  src/main/java/com/groot/mindmap/message/service/RedisService.java
  src/main/java/com/groot/mindmap/util/MessagePublisher.java
  src/main/java/com/groot/mindmap/util/StompHandler.java
Labels: enhancement

#6 fix(MS-27): 리뷰 피드백 반영 및 메세지 전송 오류 수정
  src/main/java/com/groot/mindmap/message/controller/MessageController.java
  src/main/java/com/groot/mindmap/message/domain/AddMessage.java
  src/main/java/com/groot/mindmap/message/domain/DeleteMessage.java
  src/main/java/com/groot/mindmap/message/domain/Message.java
  src/main/java/com/groot/mindmap/message/domain/NodeListMessage.java
  src/main/java/com/groot/mindmap/message/domain/UserListMessage.java
  src/main/java/com/groot/mindmap/message/repository/RedisRepository.java
  src/main/java/com/groot/mindmap/message/service/MessageService.java
  src/main/java/com/groot/mindmap/util/MessagePublisher.java
  src/main/java/com/groot/mindmap/util/StompHandler.java
Labels: bug, refactoring

#7 feat(MS-38): 소셜 로그인 기능 추가
  build.gradle
  src/main/java/com/groot/mindmap/config/Oauth2LoginSecurityConfiguration.java
  src/main/java/com/groot/mindmap/user/domain/AuthInformation.java
  src/main/java/com/groot/mindmap/user/domain/AuthInformationFactory.java
Labels: enhancement

#8 feat(MS-37): User 생성 기능 추가
  src/main/java/com/groot/mindmap/user/domain/User.java
  src/main/java/com/groot/mindmap/user/repository/UserRepository.java
  src/main/java/com/groot/mindmap/user/service/UserService.java
Labels: enhancement

#9 feat(MS-37): 최초 로그인 시 유저를 생성하는 기능 추가
  src/main/java/com/groot/mindmap/config/Oauth2LoginSecurityConfiguration.java
  src/main/java/com/groot/mindmap/user/domain/User.java
  src/main/java/com/groot/mindmap/user/repository/UserRepository.java
  src/main/java/com/groot/mindmap/user/service/UserService.java
Labels: enhancement

#10 feat(MS-27): Node 반환 자료구조 변경 및 로그인 기능에 대한 추가 구현
  src/main/java/com/groot/mindmap/config/WebSecurityConfiguration.java
  src/main/java/com/groot/mindmap/message/controller/MessageController.java
  src/main/java/com/groot/mindmap/message/domain/NodeListMessage.java
  src/main/java/com/groot/mindmap/message/service/MessageService.java
  src/main/java/com/groot/mindmap/node/domain/Node.java
  src/main/java/com/groot/mindmap/node/dto/NodeRequest.java
  src/main/java/com/groot/mindmap/node/dto/NodeResponse.java
  src/main/java/com/groot/mindmap/node/service/NodeService.java
  src/main/java/com/groot/mindmap/user/domain/AuthInformationFactory.java
  src/main/java/com/groot/mindmap/util/StompHandler.java
Labels: enhancement

#11 refactor(MS-27): 로그인 성공 및 실패시 리다이렉트 되는 주소를 환경 변수로 사용하도록 변경
  src/main/java/com/groot/mindmap/config/WebSecurityConfiguration.java
Labels: refactoring

#12 refactor(MS-27): Allowed Origin 주소를 환경 변수로 사용하도록 변경
  src/main/java/com/groot/mindmap/config/WebSecurityConfiguration.java
Labels: refactoring
