Repository Groot-GT/groot-server, pull requests merged in 2023-06, with the labels that each got.

#13 feat(MS-42): Page 도메인 추가 및 Node와의 연관 기능 구현
  src/main/java/com/groot/mindmap/MindmapApplication.java
  src/main/java/com/groot/mindmap/exception/ControllerAdvice.java
  src/main/java/com/groot/mindmap/message/domain/NodeListMessage.java
  src/main/java/com/groot/mindmap/message/service/MessageService.java
  src/main/java/com/groot/mindmap/node/controller/NodeController.java
  src/main/java/com/groot/mindmap/node/domain/Node.java
  src/main/java/com/groot/mindmap/node/repository/NodeRepository.java
  src/main/java/com/groot/mindmap/node/service/NodeService.java
  src/main/java/com/groot/mindmap/page/controller/PageController.java
  src/main/java/com/groot/mindmap/page/domain/Page.java
  src/main/java/com/groot/mindmap/page/repository/PageRepository.java
  src/main/java/com/groot/mindmap/page/service/PageService.java
  src/main/java/com/groot/mindmap/util/BaseTimeEntity.java
Labels: enhancement

#14 docs(MS-35): Spring REST Docs 적용
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/resources/static/docs/index.html
  src/test/java/com/groot/mindmap/node/controller/NodeControllerTest.java
  src/test/java/com/groot/mindmap/page/controller/PageControllerTest.java
Labels: documentation

#15 refactoring(MS-39): 개발 단계에서 인증을 하지 않아도 되도록 변경
  build.gradle
  src/main/java/com/groot/mindmap/config/WebSecurityConfiguration.java
  src/main/java/com/groot/mindmap/message/domain/NodeListMessage.java
  src/main/java/com/groot/mindmap/node/controller/NodeController.java
  src/main/java/com/groot/mindmap/node/service/NodeService.java
  src/main/java/com/groot/mindmap/util/StompHandler.java
Labels: refactoring
